### ISSUE TITLE
tested EStore on latest web2py stable but not working.

### ISSUE THREAD

**Issue by v3ss0n** [mdipierro/web2py-appliances#12]
Is that due to Compatibility problem ?

**Comment by mdipierro** [comment]
can you post the error?

**Comment by mdipierro** [comment]
also look into https://github.com/mdipierro/estore3

**Comment by v3ss0n** [comment]
Estore3 works fine! 

Estore2 error was :
Traceback (most recent call last):
  File "/home/v3ss/Experiments/web2py/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/home/v3ss/Experiments/web2py/applications/estore/models/db1.py", line 91, in <module>
    db.inventory) # copy the prodoct, in case changes
  File "/home/v3ss/Experiments/web2py/gluon/packages/dal/pydal/base.py", line 834, in define_table
    table = self.lazy_define_table(tablename,_fields,_*args)
  File "/home/v3ss/Experiments/web2py/gluon/packages/dal/pydal/base.py", line 873, in lazy_define_table
    polymodel=polymodel)
  File "/home/v3ss/Experiments/web2py/gluon/packages/dal/pydal/adapters/base.py", line 297, in create_table
    raise KeyError('Cannot resolve reference %s in %s definition' % (referenced, table._tablename))
KeyError: 'Cannot resolve reference invoice in invoice_item definition'
